// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD97jJSV3rpxFysfCiPXtNHPVhiAOvm65o',
    appId: '1:669329188204:web:59f8336ba709ed3294ff49',
    messagingSenderId: '669329188204',
    projectId: 'petsselling-d3076',
    authDomain: 'petsselling-d3076.firebaseapp.com',
    storageBucket: 'petsselling-d3076.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2kEksJvO31JBJNdKklBzUHTxNpVTvMY',
    appId: '1:669329188204:android:15ee146a7ec2bc3594ff49',
    messagingSenderId: '669329188204',
    projectId: 'petsselling-d3076',
    storageBucket: 'petsselling-d3076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxM4zbxGvntCfKxOwM33mt3jIr7WEw4Y',
    appId: '1:669329188204:ios:a7161d3c4b44d5a194ff49',
    messagingSenderId: '669329188204',
    projectId: 'petsselling-d3076',
    storageBucket: 'petsselling-d3076.firebasestorage.app',
    iosBundleId: 'com.example.petsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxM4zbxGvntCfKxOwM33mt3jIr7WEw4Y',
    appId: '1:669329188204:ios:a7161d3c4b44d5a194ff49',
    messagingSenderId: '669329188204',
    projectId: 'petsselling-d3076',
    storageBucket: 'petsselling-d3076.firebasestorage.app',
    iosBundleId: 'com.example.petsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD97jJSV3rpxFysfCiPXtNHPVhiAOvm65o',
    appId: '1:669329188204:web:b245bbbf5f8cd29094ff49',
    messagingSenderId: '669329188204',
    projectId: 'petsselling-d3076',
    authDomain: 'petsselling-d3076.firebaseapp.com',
    storageBucket: 'petsselling-d3076.firebasestorage.app',
  );
}
