name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  flutter_test:
    name: Flutter Unit & Widget Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install JUnitReport
        run: dart pub global activate junitreport

      - name: Run Tests and Generate Report
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          flutter test --machine | tojunit -o flutter-test-report.xml

      - name: Publish Flutter Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: flutter-test-report.xml
          check_name: "Flutter Test Results"

  load_test:
    name: K6 Load Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 load test and Generate Report
        run: k6 run --out junit=k6-test-report.xml load_tests/k6_load_test.js

      - name: Publish K6 Load Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: k6-test-report.xml
          check_name: "K6 Load Test Results"
