name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium_tests:
    name: Selenium Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest pytest-excel

      - name: Run Selenium Tests
        run: pytest tests_dummy/test_selenium.py --excelreport=selenium_report.xlsx -q

      - name: Upload Excel Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Selenium-Excel-Report
          path: selenium_report.xlsx

  appium_tests:
    name: Appium Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest pytest-excel

      - name: Run Appium Tests
        run: pytest tests_dummy/test_appium.py --excelreport=appium_report.xlsx -q

      - name: Upload Excel Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Appium-Excel-Report
          path: appium_report.xlsx

  load_tests:
    name: K6 Load Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 load tests
        run: k6 run --out csv=k6_report.csv load_tests/k6_300.js

      - name: Upload Excel (CSV) Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: K6-Excel-CSV-Report
          path: k6_report.csv
